/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xYHqD5MkVkT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Navbar() {
  return (
    <nav className="shadow-md shadow-neutral-800 bg-white">
      <div className="w-full px-12 py-2">
        <div className="flex justify-between h-14 items-center">
          <Link href="#" className="flex items-center" prefetch={false}>
            <h1 className="font-bold text-3xl text-black">EthPay</h1>
          </Link>
          <nav className="hidden md:flex gap-8 ml-12 text-black">
            <Link
              href="#"
              className="font-semibold flex items-center text-lg transition-colors hover:underline"
              prefetch={false}
            >
              Home
            </Link>
            <Link
              href="#"
              className="font-semibold flex items-center text-lg transition-colors hover:underline"
              prefetch={false}
            >
              About
            </Link>
            <Link
              href="#"
              className="font-semibold flex items-center text-lg transition-colors hover:underline"
              prefetch={false}
            >
              Services
            </Link>
            <Link
              href="#"
              className="font-semibold flex items-center text-lg transition-colors hover:underline"
              prefetch={false}
            >
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-8">
            <Link href="/login">
            <Button size="lg" className="shadow-sm font-semibold shadow-grey-800 border-2 border-gray-700 hover:border-white">
              Sign in
            </Button>
            </Link>
            <Link href="/signup">
              <Button variant="secondary" size="lg" className="font-semibold">Sign up</Button>
            </Link>
            
          </div>
        </div>
      </div>
    </nav>
  )
}

